# Change these first
owner: Motimate # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Web application
    url: https://motimate.app/signin
    headers:
      - "User-Agent: $USER_AGENT"
  - name: Landing page
    url: https://www.motimateapp.com/
    headers:
      - "User-Agent: $USER_AGENT"

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.motimateapp.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://res.cloudinary.com/motimate-dev/image/upload/t_media_lib_thumb/v1609411794/hsbgfpvmhuc3mg4bypf1.png
  name: Motimate
  introTitle: "**Motimate** is the fun and easy mobile learning app that brings together a world full of knowledge."
  introMessage: Overview of the status of our pages.
  navbar:
    - title: Status
      href: /
    - title: Help Center
      href: https://support.motimateapp.com/
    - title: Support
      href: https://www.motimateapp.com/customer-support/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
